version: "3"

services:
  spring:
    image: ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}:${DOCKER_TAG}
    container_name: spring-container-prod
    ports:
      - "8082:8080"
    env_file:
      - spring.env