version: "3"

services:
  spring:
    build: ../..
    image: spring-image-local
    container_name: spring-container-local
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - MY_SECRET=locallocal

#services:
#  spring:
#    image: ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}:${DOCKER_TAG}
#    container_name: ${DOCKER_TAG}
#    ports:
#      - "8080:8080"
#    # 노출되도 되는 환경변수
#    environment:
#      - SPRING_PROFILES_ACTIVE=local
#    # 노출되면 안되는 환경변수
#    env_file:
#      - spring.env


# -------------------------------------

# 도커 컴포즈 생성 + 실행 : docker-compose -p spring-compose up -d
# 도커 컴포즈 종료 : docker-compose -p spring-compose stop
# 도커 컴포즈 재실행 : docker-compose -p spring-compose start
# 도커 컴포즈 종료 + 삭제 : docker-compose -p spring-compose down