version: "3"

services:
  spring:
    build: ..
    image: spring-image
    container_name: spring-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MY_SECRET=prodprod

#services:
#  spring:
#    image: ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}:${DOCKER_TAG}
#    container_name: spring-cont
#    ports:
#      - "8080:8080"
#    env_file:
#      - spring.env


# -------------------------------------

# 도커 컴포즈 생성 + 실행 : docker-compose -p spring-compose up -d
# 도커 컴포즈 종료 : docker-compose -p spring-compose stop
# 도커 컴포즈 재실행 : docker-compose -p spring-compose start
# 도커 컴포즈 종료 + 삭제 : docker-compose -p spring-compose down