#name: cd-prod
#
#on:
#  push:
#    branches: [ "main" ]

jobs:
  deploy-ec2:
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_HOST }}
          port: ${{ secrets.EC2_INSTANCE_PORT }}
          username: ${{ secrets.EC2_INSTANCE_USERNAME }}
          key: ${{ secrets.EC2_INSTANCE_PRIVATE_KEY }}
          # 서버 문따고 들어가서 뭐할건데
          script: | 
            cd /srv/cicd-test
            git pull origin main
            ./gradlew build
            cd ./build/libs
            java -DMY_SECRET=${{ secrets.MY_SECRET }} -jar cicd-test-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod
