#name: cd
#
#on:
#  push:
#    branches: [ "dev" ]
#
#jobs:
#  deploy-ec2:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Deploy to Oracle Cloud
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.EC2_INSTANCE_HOST }}
#          port: ${{ secrets.EC2_INSTANCE_PORT }}
#          username: ${{ secrets.EC2_INSTANCE_USERNAME }}
#          key: ${{ secrets.EC2_INSTANCE_PRIVATE_KEY }}
#          script: |
