name: ci-push

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  update-sonar-report:
    runs-on: ubuntu-latest
    steps:
      - name: github 체크아웃
        uses: actions/checkout@v3

      - name: jdk 세팅
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: SonarCloud 결과물 캐싱하기
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # 테스트에서 터지면 sonar 명령어도 취소됨 -> 반드시 PR에서 테스트가 완벽히 검증된 상태여야 함.
      - name: gradle 빌드 + 테스트 -> SonarCloud branch 업데이트
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build sonar --info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
