# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: ci

on:
  pull_request:
    branches: [ "main", "dev" ]

# 이렇게 안하고 repository settings 에서 설정해도 된다.
permissions:
  checks: write
  pull-requests: write

jobs:
  build-gradle-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: github 체크아웃
        uses: actions/checkout@v3

      - name: jdk 세팅
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # https://github.com/gradle/gradle-build-action
      - name: gradle 빌드하기
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          # 기본적으로 캐싱은 활성화되어 있음 (안건드려도 됨)
#          cache-read-only: true
#          cache-write-only: true

      # https://github.com/EnricoMi/publish-unit-test-result-action
      - name: 테스트 결과를 PR 코멘트에 자동 작성
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()  # 실패 여부 상관없이 항상 실행~
        with:
          files: build/test-results/test/TEST-*.xml

      # https://github.com/mikepenz/action-junit-report
      - name: 테스트 코드 중 테스트 실패한 부분에 PR 코멘트 자동 작성
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: /build/test-results/test/TEST-*.xml

      # https://github.com/8398a7/action-slack
      - name: 빌드 실패시 slack 알람 보내기
        uses: 8398a7/action-slack@v3
        if: failure()
        with:
          status: ${{ job.status }}
          fields: repo, message, commit, author, action, eventName, ref, workflow, job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_URL_CICD }}