name: test

on: workflow_dispatch

jobs:
  test-job-1:
#    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: 환경변수 확인
        run: echo ${{ secrets.MY_SECRET }} | sed 's/./& /g'

      - name: dummy 파일 생성
        run: echo '#!/bin/sh' >> dummy.txt

      - name: job 간 파일 공유 - 스토리지 업로드
        uses: actions/upload-artifact@v3
        with:
          name: dummy       # key
          path: dummy.txt   # 업로드 target 파일 경로

  test-job-2:
    runs-on: ubuntu-latest
    needs: [ test-job-1 ]
    steps:
      - name: dummy 파일 다운로드
        uses: actions/download-artifact@v2
        with:
          name: dummy   # key
          path: temp    # 다운로드받을 경로

      - name: 파일 확인하기
        run: pwd ; ls
