name: test

on: workflow_dispatch

jobs:
  test:
#    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: 환경변수 확인
        run: |
          echo ${{ secrets.MY_SECRET }} | sed 's/./& /g'
